+incdir+../../rtl/common
../../rtl/axi/axi4_slave_if.v
../../rtl/axi/axi4_master_write.v
../../rtl/control/accel_regfile.v
../../rtl/control/accel_scheduler.v
../../rtl/control/perf_counter.v
../../rtl/memory/asic_sram_1024x16.v
../../rtl/memory/asic_sram_256xwide.v
../../rtl/memory/banked_sram.v
../../rtl/memory/bram_buffer.v
../../rtl/memory/output_buffer.v
../../rtl/memory/pingpong_buffer.v
../../rtl/memory/qkv_tile_cache.v
../../rtl/memory/stream_fifo.v
../../rtl/memory/uram_bank.v
../../rtl/compute/scale_requant_unit.v
../../rtl/compute/os_fsa_pe.v
../../rtl/compute/os_fsa_array.v
../../rtl/compute/os_fsa_controller.v
../../rtl/compute/qk_engine.v
../../rtl/compute/pv_engine.v
../../rtl/softmax/causal_mask.v
../../rtl/softmax/row_broadcast.v
../../rtl/softmax/row_reduce_unit.v
../../rtl/softmax/pwl_exp_unit.v
../../rtl/softmax/block_lse_update.v
../../rtl/softmax/reciprocal_lut.v
../../rtl/softmax/online_normalizer.v
../../rtl/softmax/softmax_engine.v
../../rtl/attention_accel_top.v
